### ISSUE TITLE
Questions on Colab notebook #2 (the one not requiring an A100)

### ISSUE THREAD

**Issue by metaphorz** [camenduru/I2VGen-XL-colab#6]
I tried the Colab after selecting a V100. It worked and gave me 4s worth of video but there was no box to enter a text prompt. Also, how does one get video that lasts longer?

**Comment by camenduru** [comment]
please use I2VGen_XL_Vid2Vid_colab for text prompt, for longer videos please check https://github.com/modelscope/modelscope pipeline

**Comment by metaphorz** [comment]
Thanks will do thatPaul Fishwick, Ph.D.Chair Emeritus of Arts, Humanities, and Technology (AHT)Former Professor of Computer Science (UF and UTD)CEO Metaphorz, LLC ***@***.*** Sep 21, 2023, at 9:56 PM, camenduru ***@***.***> wrote:﻿
please use I2VGen_XL_Vid2Vid_colab for text prompt, for longer videos please check https://github.com/modelscope/modelscope pipeline
